# Site settings
title: "Brandon Pomeroy"
email: brandon@pomeroyb.com
description: "A personal blog for Brandon Pomeroy"
baseurl: ""
url: "http://pomeroyb.com"
title_description: "3D Printing specialist, formally trained in Materials Science and Engineering at the University of Washington. Experience with the whole spectrum of the 3D Printing toolchain, from electronics to plastic. Other interests include VR, playing TF2, and taking things apart."
title_image: "/images/brandon.jpg"
#google_analytics: "UA-20365477-4"
disqus_account: pomeroyB
github_repository: https://github.com/pomeroyB/carte-noire
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: AchillePomeroy
github_username:  PomeroyB
email_link: brandon@pomeroyb.com
steam_link: http://steamcommunity.com/id/AchillePomeroy/
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: brandon@pomeroyb.com
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Carte Noire theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor, "s3_website.yml"]

highlighter: rouge
